/**
 * Regenerate src/seed.ts from the live sources:
 *   node scripts/generate-seed.ts
 *
 * The seed is the catalog every user already gets on a normal first run;
 * it only needs to exist for the first run without network.
 */

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import {
  buildCatalog,
  DEFAULT_API_BASE,
  MODELS_DEV_URL,
  parseModelsDev,
  parseRecommendedModels,
  RECOMMENDED_MODELS_ENDPOINT,
} from "../src/discovery.ts";

const apiBase = process.env.CLINE_API_BASE?.trim() || DEFAULT_API_BASE;

const [liveResponse, devResponse] = await Promise.all([
  fetch(`${apiBase}${RECOMMENDED_MODELS_ENDPOINT}`),
  fetch(MODELS_DEV_URL),
]);
if (!liveResponse.ok) throw new Error(`recommended-models: HTTP ${liveResponse.status}`);
if (!devResponse.ok) throw new Error(`models.dev: HTTP ${devResponse.status}`);

const live = parseRecommendedModels(await liveResponse.json());
const dev = parseModelsDev(await devResponse.json());
if (live.length === 0) throw new Error("recommended-models returned no models");

const models = buildCatalog(live, dev);
const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "src", "seed.ts");

const banner = `/**
 * Bundled fallback catalog, regenerated by \`npm run generate-seed\`.
 *
 * Generated at ${new Date().toISOString()} from:
 *   ${apiBase}${RECOMMENDED_MODELS_ENDPOINT}
 *   ${MODELS_DEV_URL}
 *
 * Only used when neither the on-disk cache nor the network is available.
 */

import type { CatalogEntry } from "./discovery.ts";

export const SEED_CATALOG: CatalogEntry[] = ${JSON.stringify(models, null, 2)};
`;

writeFileSync(out, banner, "utf8");
console.log(`wrote ${models.length} models to ${out}`);
