/**
 * Bundled fallback catalog, regenerated by `npm run generate-seed`.
 *
 * Generated at 2026-09-27T01:40:13.280Z from:
 *   https://api.cline.bot/api/v1/ai/cline/recommended-models
 *   https://models.dev/api.json
 *
 * Only used when neither the on-disk cache nor the network is available.
 */

import type { CatalogEntry } from "./discovery.ts";

export const SEED_CATALOG: CatalogEntry[] = [
  {
    "id": "cline-pass/mimo-v2.6-flash",
    "name": "MiMo-V2.6-Flash",
    "reasoning": true,
    "input": [
      "text",
      "image"
    ],
    "cost": {
      "input": 0.14,
      "output": 0.28,
      "cacheRead": 0.0028,
      "cacheWrite": 0
    },
    "contextWindow": 1048576,
    "maxTokens": 131072,
    "thinkingLevelMap": {
      "off": "none",
      "minimal": null,
      "low": "low",
      "medium": "medium",
      "high": "high",
      "xhigh": "xhigh",
      "max": null
    },
    "compat": {
      "supportsDeveloperRole": false,
      "cacheControlFormat": "anthropic",
      "supportsLongCacheRetention": false
    }
  },
  {
    "id": "cline-pass/mimo-v2.6-pro",
    "name": "MiMo-V2.6-Pro",
    "reasoning": true,
    "input": [
      "text",
      "image"
    ],
    "cost": {
      "input": 0.435,
      "output": 0.87,
      "cacheRead": 0.0036,
      "cacheWrite": 0
    },
    "contextWindow": 1048576,
    "maxTokens": 131072,
    "thinkingLevelMap": {
      "off": "none",
      "minimal": null,
      "low": "low",
      "medium": "medium",
      "high": "high",
      "xhigh": "xhigh",
      "max": null
    },
    "compat": {
      "supportsDeveloperRole": false,
      "cacheControlFormat": "anthropic",
      "supportsLongCacheRetention": false
    }
  },
  {
    "id": "cline-pass/glm-5.3",
    "name": "GLM-5.3",
    "reasoning": true,
    "input": [
      "text"
    ],
    "cost": {
      "input": 1.4,
      "output": 4.4,
      "cacheRead": 0.26,
      "cacheWrite": 0
    },
    "contextWindow": 1000000,
    "maxTokens": 131072,
    "thinkingLevelMap": {
      "off": null,
      "minimal": null,
      "low": "low",
      "medium": null,
      "high": "high",
      "xhigh": null,
      "max": "max"
    },
    "compat": {
      "supportsDeveloperRole": false,
      "cacheControlFormat": "anthropic",
      "supportsLongCacheRetention": false
    }
  },
  {
    "id": "cline-pass/deepseek-v4-pro",
    "name": "DeepSeek V4 Pro",
    "reasoning": true,
    "input": [
      "text"
    ],
    "cost": {
      "input": 1.74,
      "output": 3.48,
      "cacheRead": 0.0145,
      "cacheWrite": 0
    },
    "contextWindow": 1000000,
    "maxTokens": 384000,
    "thinkingLevelMap": {
      "off": "none",
      "minimal": null,
      "low": null,
      "medium": null,
      "high": "high",
      "xhigh": null,
      "max": "max"
    },
    "compat": {
      "supportsDeveloperRole": false,
      "cacheControlFormat": "anthropic",
      "supportsLongCacheRetention": false
    }
  },
  {
    "id": "cline-pass/qwen3.8-max",
    "name": "Qwen3.8 Max",
    "reasoning": true,
    "input": [
      "text",
      "image"
    ],
    "cost": {
      "input": 2,
      "output": 6,
      "cacheRead": 0.25,
      "cacheWrite": 0
    },
    "contextWindow": 1000000,
    "maxTokens": 131072,
    "thinkingLevelMap": {
      "off": "none",
      "minimal": null,
      "low": "low",
      "medium": "medium",
      "high": null,
      "xhigh": "xhigh",
      "max": null
    },
    "compat": {
      "supportsDeveloperRole": false,
      "cacheControlFormat": "anthropic",
      "supportsLongCacheRetention": false
    }
  },
  {
    "id": "cline-pass/deepseek-v4.1-flash",
    "name": "DeepSeek V4.1 Flash",
    "reasoning": true,
    "input": [
      "text",
      "image"
    ],
    "cost": {
      "input": 0.15,
      "output": 0.6,
      "cacheRead": 0.003,
      "cacheWrite": 0
    },
    "contextWindow": 1000000,
    "maxTokens": 384000,
    "thinkingLevelMap": {
      "off": "none",
      "minimal": null,
      "low": "low",
      "medium": null,
      "high": "high",
      "xhigh": null,
      "max": "max"
    },
    "compat": {
      "supportsDeveloperRole": false,
      "cacheControlFormat": "anthropic",
      "supportsLongCacheRetention": false
    }
  },
  {
    "id": "cline-pass/muse-spark-1.3-contributor",
    "name": "Muse Spark 1.3 Contributor",
    "reasoning": true,
    "input": [
      "text",
      "image"
    ],
    "cost": {
      "input": 0,
      "output": 0,
      "cacheRead": 0,
      "cacheWrite": 0
    },
    "contextWindow": 1048576,
    "maxTokens": 131072,
    "thinkingLevelMap": {
      "off": null,
      "minimal": "minimal",
      "low": "low",
      "medium": "medium",
      "high": "high",
      "xhigh": "xhigh",
      "max": null
    },
    "compat": {
      "supportsDeveloperRole": false,
      "cacheControlFormat": "anthropic",
      "supportsLongCacheRetention": false
    }
  },
  {
    "id": "cline-pass/kimi-k3",
    "name": "Kimi K3",
    "reasoning": true,
    "input": [
      "text",
      "image"
    ],
    "cost": {
      "input": 3,
      "output": 15,
      "cacheRead": 0.3,
      "cacheWrite": 0
    },
    "contextWindow": 1048576,
    "maxTokens": 131072,
    "thinkingLevelMap": {
      "off": "none",
      "minimal": null,
      "low": "low",
      "medium": null,
      "high": "high",
      "xhigh": null,
      "max": "max"
    },
    "compat": {
      "supportsDeveloperRole": false,
      "cacheControlFormat": "anthropic",
      "supportsLongCacheRetention": false
    }
  },
  {
    "id": "cline-pass/glm-5.3-flash",
    "name": "cline-pass/glm-5.3-flash",
    "reasoning": true,
    "input": [
      "text",
      "image"
    ],
    "cost": {
      "input": 0.15,
      "output": 0.5,
      "cacheRead": 0.03,
      "cacheWrite": 0
    },
    "contextWindow": 1000000,
    "maxTokens": 131072,
    "thinkingLevelMap": {
      "off": null,
      "minimal": null,
      "low": "low",
      "medium": null,
      "high": "high",
      "xhigh": null,
      "max": "max"
    },
    "compat": {
      "supportsDeveloperRole": false,
      "cacheControlFormat": "anthropic",
      "supportsLongCacheRetention": false
    }
  },
  {
    "id": "cline-pass/minimax-m3",
    "name": "MiniMax-M3",
    "reasoning": true,
    "input": [
      "text",
      "image"
    ],
    "cost": {
      "input": 0.3,
      "output": 1.2,
      "cacheRead": 0.06,
      "cacheWrite": 0
    },
    "contextWindow": 1048576,
    "maxTokens": 512000,
    "thinkingLevelMap": {
      "off": "none",
      "minimal": null,
      "low": "low",
      "medium": "medium",
      "high": "high",
      "xhigh": null,
      "max": null
    },
    "compat": {
      "supportsDeveloperRole": false,
      "cacheControlFormat": "anthropic",
      "supportsLongCacheRetention": false
    }
  },
  {
    "id": "cline-pass/qwen3.7-plus",
    "name": "Qwen3.7 Plus",
    "reasoning": true,
    "input": [
      "text",
      "image"
    ],
    "cost": {
      "input": 0.4,
      "output": 1.6,
      "cacheRead": 0.04,
      "cacheWrite": 0
    },
    "contextWindow": 1000000,
    "maxTokens": 64000,
    "thinkingLevelMap": {
      "off": "none",
      "minimal": null,
      "low": "low",
      "medium": "medium",
      "high": "high",
      "xhigh": null,
      "max": null
    },
    "compat": {
      "supportsDeveloperRole": false,
      "cacheControlFormat": "anthropic",
      "supportsLongCacheRetention": false
    }
  },
  {
    "id": "cline-pass/qwen3.7-max",
    "name": "Qwen3.7 Max",
    "reasoning": true,
    "input": [
      "text"
    ],
    "cost": {
      "input": 2.5,
      "output": 7.5,
      "cacheRead": 0.5,
      "cacheWrite": 0
    },
    "contextWindow": 1000000,
    "maxTokens": 65536,
    "thinkingLevelMap": {
      "off": "none",
      "minimal": null,
      "low": "low",
      "medium": "medium",
      "high": "high",
      "xhigh": null,
      "max": null
    },
    "compat": {
      "supportsDeveloperRole": false,
      "cacheControlFormat": "anthropic",
      "supportsLongCacheRetention": false
    }
  },
  {
    "id": "cline-pass/mimo-v2.5-pro",
    "name": "MiMo-V2.5-Pro",
    "reasoning": true,
    "input": [
      "text"
    ],
    "cost": {
      "input": 1.74,
      "output": 3.48,
      "cacheRead": 0.0145,
      "cacheWrite": 0
    },
    "contextWindow": 1048576,
    "maxTokens": 131072,
    "thinkingLevelMap": {
      "off": "none",
      "minimal": null,
      "low": "low",
      "medium": "medium",
      "high": "high",
      "xhigh": null,
      "max": null
    },
    "compat": {
      "supportsDeveloperRole": false,
      "cacheControlFormat": "anthropic",
      "supportsLongCacheRetention": false
    }
  },
  {
    "id": "cline-pass/mimo-v2.5",
    "name": "MiMo-V2.5",
    "reasoning": true,
    "input": [
      "text",
      "image"
    ],
    "cost": {
      "input": 0.14,
      "output": 0.28,
      "cacheRead": 0.0028,
      "cacheWrite": 0
    },
    "contextWindow": 1048576,
    "maxTokens": 131072,
    "thinkingLevelMap": {
      "off": "none",
      "minimal": null,
      "low": "low",
      "medium": "medium",
      "high": "high",
      "xhigh": null,
      "max": null
    },
    "compat": {
      "supportsDeveloperRole": false,
      "cacheControlFormat": "anthropic",
      "supportsLongCacheRetention": false
    }
  }
];
